AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation template for phonebook  application
  This app runs on application load balancer
Resources:
  ALBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP for ALB #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  WebServersSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP for App only from ALB #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt ALBSecurityGroup.GroupId
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  PhoneBookDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AvailabilityZone: eu-west-3a
      BackupRetentionPeriod: 0
      CharacterSetName: utf-8
      DBInstanceClass: t2.micro #required
      DBInstanceIdentifier: PhoneBookDB
      DBName: phone_book
      Engine: mysql
      EngineVersion: 8.0.20
      MasterUserPassword: Clarusway_1
      MasterUsername: admin
      Port: 3306
      PubliclyAccessible: true
  
  WebServerLT:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateData:
        ImageId: ami-00077e3fed5089981
        InstanceType: t2.micro
        KeyName: AWS_PEMkey
        SecurityGroupIds: 
          - !GetAtt WebServersSecurityGroup.GroupId
        TagSpecifications: 
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub Web Server of ${AWS::StackName} Stack
        UserData: 
          Fn::Base64: |
            #!/bin/bash
            sudo yum update -y
            sudo yum install python3 -y
            sudo pip3 install flask
            sudo pip3 install flask-mysql
            sudo wget https://raw.githubusercontent.com/DavidChatak/python-workshop/master/projects/004-phonebook-web-application/app.py -P /home/ec2-user
            sudo wget https://raw.githubusercontent.com/DavidChatak/python-workshop/master/projects/004-phonebook-web-application/config.configDB.py -P /home/ec2-user
            sudo wget https://raw.githubusercontent.com/DavidChatak/python-workshop/master/projects/004-phonebook-web-application/templates/add-update.html -P /home/ec2-user/templates
            sudo wget https://raw.githubusercontent.com/DavidChatak/python-workshop/master/projects/004-phonebook-web-application/templates/delete.html -P /home/ec2-user/templates
            sudo wget https://raw.githubusercontent.com/DavidChatak/python-workshop/master/projects/004-phonebook-web-application/templates/index.html -P /home/ec2-user/templates
            sudo echo '{"host": "${!GetAtt PhoneBookDB.Endpoint.Address}","user": "admin","password": "Clarusway_1","db": "phone_book","port": 3306}' > config.json
            sudo python3  /home/ec2-user/app.py
  WebServersTG:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: !GetAtt WebServersSecurityGroup.VpcId
  ApplicationLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - !GetAtt ALBSecurityGroup.GroupId
      Subnets:
        - subnet-de0c31b7
        - subnet-b881d5c3
        - subnet-9fbf26d2
      Type: application
  ALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions: #required
        - TargetGroupArn: !Ref WebServersTG
          Type: forward
      LoadBalancerArn: !Ref ApplicationLoadBalancer #required
      Port: 80 #required
      Protocol: HTTP #required
  WebServerASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      AvailabilityZones:
        !GetAZs ""
      DesiredCapacity: 2
      HealthCheckGracePeriod: 90
      HealthCheckType: ELB
      LaunchTemplate:
        LaunchTemplateId: !Ref WebServerLT
        Version: !GetAtt WebServerLT.LatestVersionNumber
      MaxSize: 3 #required
      MinSize: 1 #required
      TargetGroupARNs:
        - !Ref WebServersTG
Outputs:
  WebsiteURL:
    Description: Phone Book Application Load Balancer URL
    Value: !Sub 
      - http://${ALBaddress}
      - ALBaddress: !GetAtt ApplicationLoadBalancer.DNSName