AWSTemplateFormatVersion: "2010-09-09"

Description: >
    This is cloudformation template for roman numerals application.
    This flask web application runs on EC2 allows connection from anywhere
    on port 80
Resources:
  flaskSecurityGroup:
    Type:AWS::
  
  myEC2instanceforFlask01:
    Type: AWS::EC2::Intance
    Proporties:
      ImageId: 'ami-0bfddfb1ccc3a6993'
      InstanceType: t2.micro
      KeyName: 'AWS_PEMkey'
      Tag:
        Key: Name
        Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData:
        Fn::Base64: |
                    #! /bin/bash
                    yum update -y
                    yum install python3 -y
                    pip3 install flask
                    