AWSTemplateFormatVersion: 2010-09-09
Resources:
  DavidSecgroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: secgrupformillisecondPROJE 
      GroupDescription: Allow http ssh
      SecurityGroupIngress:
        - IpProtocol: TCP
          ToPort: 80
          FromPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: TCP
          ToPort: 22
          FromPort: 22
          CidrIp: 0.0.0.0/0
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: AWS_PEMkey
      ImageId: ami-0bfddfb1ccc3a6993
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref DavidSecgroup
      UserData: !Base64 |
        #!/bin/bash
        sudo yum update -y
        sudo yum install python3 -y
        sudo pip3 install flask
        sudo wget https://raw.githubusercontent.com/DavidChatak/python-workshop/master/projects/project-2/templates/index.html -P /home/ec2-user/templates
        sudo wget https://raw.githubusercontent.com/DavidChatak/python-workshop/master/projects/project-2/templates/result.html -P /home/ec2-user/templates
        sudo wget https://raw.githubusercontent.com/DavidChatak/python-workshop/master/projects/project-2/app.py -P /home/ec2-user
        sudo python3  /home/ec2-user/app.py
      Tags:
        - Key: Name
          Value: webserver of ${AWS::StackName}
